name: Blazor.BroadcastChannel - CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build